NET-377 sdc-nat zones create poor ipnat.conf configuration

diff --git a/bin/setup-nat b/bin/setup-nat
--- a/bin/setup-nat
+++ b/bin/setup-nat
@@ -16,6 +16,8 @@
 set -o xtrace
 set -o pipefail
 
+NATCONF=/etc/ipf/ipnat.conf
+
 function fatal
 {
     local msg="$*"
@@ -35,7 +37,7 @@ function enable_ipnat
 {
     /usr/sbin/ipf -E || fatal "failed to enable ipf"
     /usr/sbin/ipnat -CF || fatal "failed to flush ipnat rules"
-    /usr/sbin/ipnat -f /etc/ipf/ipnat.conf || fatal "failed to flush ipnat rules"
+    /usr/sbin/ipnat -f $NATCONF || fatal "failed to flush ipnat rules"
 }
 
 #
@@ -60,15 +62,15 @@ function write_config
 
     first=
     for nic in $primary; do
-            [[ -n "$first" ]] && fatal "encountered multiple primary nics"
-            first="fatal"
+        [[ -n "$first" ]] && fatal "encountered multiple primary nics"
+        first="fatal"
     done
 
     mkdir -p /etc/ipf || fatal "failed to mkdir /etc/ipf"
-    echo "map $primary $subnet -> 0/32" > /etc/ipf/ipnat.conf || \
-        fatal "failed to write out ipnat.conf"
+    echo "map $primary $subnet -> 0/32 portmap tcp/udp auto" > $NATCONF || \
+        fatal "failed to write $NATCONF"
 }
 
 enable_ipv4_forwarding || fatal "failed to enable routing"
-write_config || fatal "failed to write ipnat config"
+write_config || fatal "failed to write $NATCONF"
 enable_ipnat || fatal "failed to enable ipneat"
